FROM node:22-bookworm

RUN npm install -g playwright@latest @playwright/test
RUN npx playwright install --with-deps

RUN cp -a /root/.cache/. /home/node/.cache/ && chown -R node:node /home/node/.cache

#RUN apt install -y telnet dnsutils iputils-ping

COPY ./playwright.entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 3000

CMD ["/entrypoint.sh"]
