name: Tests

on: ['push', 'pull_request']

permissions:
  contents: read

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['22.x']
        php: ['8.3', '8.4', '8.5']
        dependency-version: [prefer-stable]

    name: PHP ${{ matrix.php }} - Node ${{ matrix.node }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Setup Node ${{ matrix.node }}
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: ${{ matrix.node }}

    - name: Setup PHP
      uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v2
        coverage: xdebug

    - name: Setup Problem Matches
      run: |
        echo "::add-matcher::${{ runner.tool_cache }}/php.json"
        echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Install PHP dependencies
      run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-progress --ansi --optimize-autoloader

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Tests
      run: composer test
